export const clueTypes = {
    ONE_BEFORE_OTHER: 'ONE_BEFORE_OTHER',
    THREE_ADJACENT: 'THREE_ADJACENT',
    TWO_ADJACENT: 'TWO_ADJACENT',
    TWO_IN_SAME_COLUMN: 'TWO_IN_SAME_COLUMN',
    TWO_NOT_ADJACENT: 'TWO_NOT_ADJACENT',
    TWO_NOT_IN_SAME_COLUMN: 'TWO_NOI_IN_SAME_COLUMN',
}

export default clueTypes;